version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog
    container_name: blog-nextjs
    ports:
      - "3001:3000"
    working_dir: /home/project
    volumes:
      - ./:/home/project
